<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'ai-copilot',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '4.3.22',
    ),
    'wp-dashboard-widget-news' => array(
      'path' => 'jetpack_vendor/quadlayers/wp-dashboard-widget-news',
      'ver' => '1.0.9',
    ),
    'wp-notice-plugin-promote' => array(
      'path' => 'jetpack_vendor/quadlayers/wp-notice-plugin-promote',
      'ver' => '1.1.8',
    ),
    'wp-plugin-table-links' => array(
      'path' => 'jetpack_vendor/quadlayers/wp-plugin-table-links',
      'ver' => '1.0.8',
    ),
  ),
);
